[package]
name = "weight-meter"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
sp-std = { version = "3.0.0", default-fearures = false }
sp-io = { version = "3.0.0", default-fearures = false }
weight-meter-procedural = { path = "weight-meter-procedural" }


[features]
runtime-benchmarks = ["weight-meter-procedural/runtime-benchmarks"]
